---
title: "DPAS Reproducibility Thesis"
author: "Lian Rui"
date: "2026-09-24"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Setup


```{r packages}
library(tidyverse)
library(readxl)
library(dplyr)
library(tidyr)
library(psych) # ICC
library(ggplot2)
library(colorspace)
library(showtext)
showtext_auto()
library(GWalkR) # Tabuleu like, TODO: furrther explore
library(DataExplorer) 
library(gtsummary) # Table 1
library(kableExtra)
library(lmerTest)
library(emmeans)
library(forcats)
```


```{r Utility function}
# Path of utils
utils.path <- "~/DPAS Reproducibility/utils"

# Calculate ICC on the total DPAS score
source(file.path(utils.path, "calculate_total_icc.R"))

# Calculate the ICC on each metric (lesion)
source(file.path(utils.path, "calculate_metric_icc.R"))
```


## 2. Data import


```{r data import}
# Path of raw data
path <- "~/DPAS Reproducibility/data"

# Read the DPAS48, 48 patients DPAS by 4 raters
raw_dpas <- read_excel(
  file.path(path, "DPAS48.xlsx")
)

# Read patient age and sex
raw_pt <- read_excel(
  file.path(path, "DPAS48_pt_info.xls")
)
```


```{r clean DPAS}
# Rename DPAS columns
clean_dpas <- raw_dpas |>
  rename(
    Patient_id = 患者,
    Rater = 监察人
  ) |>
  rename_with(
    ~ paste0("Forehead", sub("^额", "", .x)),
    matches("^额\\d+$")
  ) |>
  rename_with(
    ~ paste0("Right_cheek", sub("^右", "", .x)),
    matches("^右\\d+$")
  ) |>
  rename_with(
    ~ paste0("Left_cheek", sub("^左", "", .x)),
    matches("^左\\d+$")
  ) |>
  rename_with(
    ~ paste0("Chin", sub("^下", "", .x)),
    matches("^下\\d+$")
  )

# Long format
clean_dpas_long <- clean_dpas |>
  pivot_longer(
    cols = 3:ncol(clean_dpas),
    names_to = "Position_metric",
    values_to = "Score"
  ) |>
  separate(
    Position_metric,
    into = c("Position", "Metric"),
    sep = "(?<=\\D)(?=\\d)",
    convert = TRUE
  )

# Cleaning patient info
clean_pt <- raw_pt |>
  rename(
    Patient_id = 姓名,
    Sex = 性别,
    Age = 年龄
  ) |>
  mutate(
    Sex = recode(
      Sex,
      "男" = "Male",
      "女" = "Female"
    )
  )
```


```{r Merge DPAS and pt_info}
# Create canonical dataset, dat_long
# and join patient info
dat_long <- clean_pt |>
  left_join(
    clean_dpas_long,
    by = "Patient_id"
  )

# data class of each column 
dat_long <- dat_long %>%
  mutate(
    Patient_id = as.character(Patient_id),
    Sex        = factor(Sex),
    Age        = as.numeric(Age), # already numeric → no-op, kept for clarity
    Rater      = factor(Rater),
    Position   = factor(Position),
    Metric     = factor(Metric),
    Score      = as.numeric(Score) # already numeric → no-op, kept for clarity
  )
```


```{r revalue Metrics}
# Revalue metrics
dat_long <- dat_long |>
  mutate(Metric = case_when(
    Metric == "1" ~ "皮肤暗黄", 
    Metric == "2" ~ "黄色丘疹",
    Metric == "3" ~ "皮肤萎缩",
    Metric == "4" ~ "痣",
    Metric == "5" ~ "色素减退-色素沉着斑",
    Metric == "6" ~ "毛细血管扩张",
    Metric == "7" ~ "脂溢性角化",
    Metric == "8" ~ "老年性粉刺",
    Metric == "9" ~ "深皱纹",
    Metric == "10" ~ "浅表皱纹",
    Metric == "11" ~ "网状皱纹"
  ))
```


```{r dat_long structure}
str(dat_long)
```


```{r missing value check}
sapply(dat_long, function(x) sum(is.na(x)))
```


```{r data summary}
summary(dat_long)
```


```{r Table 1}
table1_df <- dat_long |>
  dplyr::select(Patient_id, Sex, Age) |>
  dplyr::distinct(Patient_id, .keep_all = TRUE) |>
  gtsummary::tbl_summary(
    by = Sex,
    include = Age,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
    ),
    missing = "ifany"
  ) |>
  gtsummary::add_p() |>
  tibble::as_tibble()

table1_df
```



### 男女在11项评分中的表现和差别

```{r metric by sex}
score_sex_position_metric <- dat_long |>
  group_by(Sex, Position, Metric) |>
  summarise(n = sum(Score)/4) |>
  mutate(pct = n /48)


g <- ggplot(score_sex_position_metric,
            aes(x = fct_rev(Metric), y = pct, fill = Sex)) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(
    aes(label = percent(pct, accuracy = 1)),
    position = position_dodge(width = 0.9),
    hjust = -0.1,          # push labels just past the bar tip
    size = 3
  ) +
  scale_fill_discrete_qualitative(palette = "Harmonic") + 
  scale_y_continuous(
    labels = percent_format(accuracy = 1),
    breaks = seq(0, 1, 0.2),
    expand = expansion(mult = c(0, 0.1)), # room for labels at the end
    limits = c(0, 0.5)
  ) +
  labs(
    title = "不同光老化皮损类型在男女四个部位的发生率",
    x = "光老化类型",
    y = "发生率"
  ) + 
  coord_flip() +
  facet_grid(. ~ Position) +
  theme_classic(base_size = 12) +
  theme(
    legend.position = "top",
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank()
  )

g
```


```{r total score}
dat_total_rater <- dat_long |>
  group_by(Patient_id, Rater, Sex, Age) |>
  summarise(
    Total = sum(Score, na.rm = TRUE),
    .groups = "drop"
  )
```


```{r total icc}
icc_total <- calculate_total_icc(dat_total_rater)

icc_total$results
```

### Metric specific ICC

```{r metric specific score}
dat_metric_specific_rater <- dat_long |>
  group_by(Patient_id, Rater, Sex, Age, Metric) |>
  summarise(
    Total = sum(Score, na.rm = TRUE),
    .groups = "drop"
  )
```


```{r metric icc}
icc_metric <- calculate_metric_icc(dat_metric_specific_rater)

icc_metric
```

## 8. Linear Mixed effect model

### Create dat_model for logistic mixed model

```{r dat_model}
dat_model <- dat_long |>
  mutate(
    Age_c = Age - mean(Age, na.rm = TRUE),
    Metric = factor(Metric),
    Position = factor(Position),
    Sex = factor(Sex)
  )

# Remove metric 3, which does not occur among all patients
# Inclusion of metric 3 lead to singular fitting
dat_model <- dat_model |>
  filter(!Metric == 3)
```


```{r glmer fit}
fit <- glmer(
  Score ~ Position + Age + Metric * Sex  + 
    (1 | Rater) + (1 | Patient_id),
  data = dat_model,
  family = binomial
)

# 3. Check convergence
isSingular(fit)
summary(fit)
```

### emmeans summary of fit

```{r}
emm_sex <- emmeans(
  fit, 
  ~ Sex | Metric, 
  type = "response"
)

pairs(emm_sex, reverse = TRUE)
```

```{r}
emm_prob <- emmeans(
  fit,
  ~ Sex | Metric,
  type = "response"
) |>
  as.data.frame()

metric_order <- emm_prob |>
  dplyr::group_by(Metric) |>
  dplyr::summarise(
    mean_prob = mean(prob),
    .groups = "drop"
  ) |>
  dplyr::arrange(mean_prob) |>
  dplyr::pull(Metric)

emm_prob <- emm_prob |>
  dplyr::mutate(
    Metric = factor(Metric, levels = metric_order)
  )
```

```{r}
library(ggplot2)
library(scales)

ggplot(
  emm_prob,
  aes(x = prob, y = Metric, color = Sex, shape = Sex)
) +
  geom_errorbar(
    aes(
      xmin = asymp.LCL,
      xmax = asymp.UCL
    ),
    orientation = "y",
    position = position_dodge(width = 0.5),
    height = 0.15,
    linewidth = 0.7
  ) +
  geom_point(
    position = position_dodge(width = 0.5),
    size = 3
  ) +
  geom_hline(
    yintercept = seq(
      1.5,
      nlevels(emm_prob$Metric) - 0.5,
      by = 1
    ),
    color = "grey90",
    linewidth = 0.3,
    linetype = "dashed"
  ) +
  scale_x_continuous(
    labels = scales::percent_format(accuracy = 1),
    limits = c(0, 0.75),
    expand = expansion(mult = c(0.02, 0.05))
  ) +
  scale_color_discrete_qualitative(palette = "Harmonic") + 
  labs(
    x = "Estimated probability of lesion presence",
    y = "DPAS metric",
    color = "Sex"
  ) +
  theme_classic(base_size = 12) +
  theme(
    legend.position = "top",
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank()
  )
```


### Model selection with/without the interaction of metric and sex

```{r model selection ANOVA}
# fit 1: no interaction of metric and sex
fit1 <- glmer(
  Score ~ Metric + Position + Sex + Age_c +
    (1 | Rater) + 
    (1 | Patient_id),
  data = dat_model,
  family = binomial
)

# fit 2: with interaction of metric and sex
fit2 <- glmer(
  Score ~ Metric + Position + Sex + Age_c + Metric * Sex +
    (1 | Rater) + 
    (1 | Patient_id),
  data = dat_model,
  family = binomial
)

# Compare Anova of two fits
anova(fit1, fit2, test = "Chisq")
## Interaction is meaningful!
```



